@startuml


class Mediator.Chatroom implements Mediator.Mediator {
- ArrayList<Colleague> colleagues
+ void addColleague(Colleague)
+ void send(Colleague,String,Colleague)
+ void send(Colleague,String)
+ ArrayList<Colleague> getColleagues()
}

class Mediator.ConcreteColleague implements Mediator.Colleague{
~ String name
~ Mediator mediator
+ void setMediator(Mediator)
+ String getName()
+ void receive(String,Colleague)
}

interface Mediator.Mediator {
+ void send(Colleague,String,Colleague)
+ void send(Colleague,String)
}

interface Mediator.Colleague {
+ void setMediator(Mediator)
+ String getName()
~ void receive(String,Colleague)
}

@enduml